// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/orchestrator.proto

package pb_orchestrator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestratorService_GetExpressions_FullMethodName    = "/orchestrator.OrchestratorService/GetExpressions"
	OrchestratorService_GetExpressionById_FullMethodName = "/orchestrator.OrchestratorService/GetExpressionById"
	OrchestratorService_AddToQueue_FullMethodName        = "/orchestrator.OrchestratorService/AddToQueue"
	OrchestratorService_GiveTask_FullMethodName          = "/orchestrator.OrchestratorService/GiveTask"
	OrchestratorService_AnswerTask_FullMethodName        = "/orchestrator.OrchestratorService/AnswerTask"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorServiceClient interface {
	GetExpressions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Expression], error)
	GetExpressionById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Expression, error)
	AddToQueue(ctx context.Context, in *StringExpression, opts ...grpc.CallOption) (*Expression, error)
	GiveTask(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Task, error)
	AnswerTask(ctx context.Context, in *Answer, opts ...grpc.CallOption) (*Empty, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) GetExpressions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Expression], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestratorService_ServiceDesc.Streams[0], OrchestratorService_GetExpressions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Expression]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorService_GetExpressionsClient = grpc.ServerStreamingClient[Expression]

func (c *orchestratorServiceClient) GetExpressionById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Expression, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Expression)
	err := c.cc.Invoke(ctx, OrchestratorService_GetExpressionById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) AddToQueue(ctx context.Context, in *StringExpression, opts ...grpc.CallOption) (*Expression, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Expression)
	err := c.cc.Invoke(ctx, OrchestratorService_AddToQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) GiveTask(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, OrchestratorService_GiveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) AnswerTask(ctx context.Context, in *Answer, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, OrchestratorService_AnswerTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
type OrchestratorServiceServer interface {
	GetExpressions(*Empty, grpc.ServerStreamingServer[Expression]) error
	GetExpressionById(context.Context, *Id) (*Expression, error)
	AddToQueue(context.Context, *StringExpression) (*Expression, error)
	GiveTask(context.Context, *Empty) (*Task, error)
	AnswerTask(context.Context, *Answer) (*Empty, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) GetExpressions(*Empty, grpc.ServerStreamingServer[Expression]) error {
	return status.Errorf(codes.Unimplemented, "method GetExpressions not implemented")
}
func (UnimplementedOrchestratorServiceServer) GetExpressionById(context.Context, *Id) (*Expression, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExpressionById not implemented")
}
func (UnimplementedOrchestratorServiceServer) AddToQueue(context.Context, *StringExpression) (*Expression, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToQueue not implemented")
}
func (UnimplementedOrchestratorServiceServer) GiveTask(context.Context, *Empty) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GiveTask not implemented")
}
func (UnimplementedOrchestratorServiceServer) AnswerTask(context.Context, *Answer) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerTask not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_GetExpressions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServiceServer).GetExpressions(m, &grpc.GenericServerStream[Empty, Expression]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestratorService_GetExpressionsServer = grpc.ServerStreamingServer[Expression]

func _OrchestratorService_GetExpressionById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GetExpressionById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GetExpressionById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GetExpressionById(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_AddToQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringExpression)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).AddToQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_AddToQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).AddToQueue(ctx, req.(*StringExpression))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_GiveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).GiveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_GiveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).GiveTask(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_AnswerTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Answer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).AnswerTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_AnswerTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).AnswerTask(ctx, req.(*Answer))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExpressionById",
			Handler:    _OrchestratorService_GetExpressionById_Handler,
		},
		{
			MethodName: "AddToQueue",
			Handler:    _OrchestratorService_AddToQueue_Handler,
		},
		{
			MethodName: "GiveTask",
			Handler:    _OrchestratorService_GiveTask_Handler,
		},
		{
			MethodName: "AnswerTask",
			Handler:    _OrchestratorService_AnswerTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetExpressions",
			Handler:       _OrchestratorService_GetExpressions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/orchestrator.proto",
}
