// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protos/orchestrator.proto

package pb_orchestrator

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_StatusPending    Status = 0
	Status_StatusInProgress Status = 1
	Status_StatusCompleted  Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "StatusPending",
		1: "StatusInProgress",
		2: "StatusCompleted",
	}
	Status_value = map[string]int32{
		"StatusPending":    0,
		"StatusInProgress": 1,
		"StatusCompleted":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_orchestrator_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protos_orchestrator_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protos_orchestrator_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protos_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_orchestrator_proto_rawDescGZIP(), []int{0}
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_protos_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_protos_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_protos_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StringExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expr          string                 `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringExpression) Reset() {
	*x = StringExpression{}
	mi := &file_protos_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringExpression) ProtoMessage() {}

func (x *StringExpression) ProtoReflect() protoreflect.Message {
	mi := &file_protos_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringExpression.ProtoReflect.Descriptor instead.
func (*StringExpression) Descriptor() ([]byte, []int) {
	return file_protos_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *StringExpression) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

type Expression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=orchestrator.Status" json:"status,omitempty"`
	Result        float32                `protobuf:"fixed32,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_protos_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_protos_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_protos_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *Expression) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Expression) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_StatusPending
}

func (x *Expression) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Arg1          float32                `protobuf:"fixed32,2,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          float32                `protobuf:"fixed32,3,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Op            string                 `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`
	OpTimeMs      int64                  `protobuf:"varint,5,opt,name=op_time_ms,json=opTimeMs,proto3" json:"op_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_protos_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_protos_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_protos_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetArg1() float32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *Task) GetArg2() float32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *Task) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Task) GetOpTimeMs() int64 {
	if x != nil {
		return x.OpTimeMs
	}
	return 0
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Res           float32                `protobuf:"fixed32,2,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_protos_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_protos_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *Answer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Answer) GetRes() float32 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_protos_orchestrator_proto protoreflect.FileDescriptor

const file_protos_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x19protos/orchestrator.proto\x12\forchestrator\x1a\x1cgoogle/api/annotations.proto\"\a\n" +
	"\x05Empty\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"&\n" +
	"\x10StringExpression\x12\x12\n" +
	"\x04expr\x18\x01 \x01(\tR\x04expr\"b\n" +
	"\n" +
	"Expression\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.orchestrator.statusR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x02R\x06result\"l\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04arg1\x18\x02 \x01(\x02R\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x03 \x01(\x02R\x04arg2\x12\x0e\n" +
	"\x02op\x18\x04 \x01(\tR\x02op\x12\x1c\n" +
	"\n" +
	"op_time_ms\x18\x05 \x01(\x03R\bopTimeMs\"*\n" +
	"\x06Answer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03res\x18\x02 \x01(\x02R\x03res*F\n" +
	"\x06status\x12\x11\n" +
	"\rStatusPending\x10\x00\x12\x14\n" +
	"\x10StatusInProgress\x10\x01\x12\x13\n" +
	"\x0fStatusCompleted\x10\x022\xdf\x03\n" +
	"\x13OrchestratorService\x12^\n" +
	"\x0eGetExpressions\x12\x13.orchestrator.Empty\x1a\x18.orchestrator.Expression\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/expressions0\x01\x12a\n" +
	"\x11GetExpressionById\x12\x10.orchestrator.Id\x1a\x18.orchestrator.Expression\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/expressions/{id}\x12d\n" +
	"\n" +
	"AddToQueue\x12\x1e.orchestrator.StringExpression\x1a\x18.orchestrator.Expression\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/calculate\x12K\n" +
	"\bGiveTask\x12\x13.orchestrator.Empty\x1a\x12.orchestrator.Task\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/internal/task\x12R\n" +
	"\n" +
	"AnswerTask\x12\x14.orchestrator.Answer\x1a\x13.orchestrator.Empty\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/internal/taskB\x12Z\x10/pb_orchestratorb\x06proto3"

var (
	file_protos_orchestrator_proto_rawDescOnce sync.Once
	file_protos_orchestrator_proto_rawDescData []byte
)

func file_protos_orchestrator_proto_rawDescGZIP() []byte {
	file_protos_orchestrator_proto_rawDescOnce.Do(func() {
		file_protos_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_orchestrator_proto_rawDesc), len(file_protos_orchestrator_proto_rawDesc)))
	})
	return file_protos_orchestrator_proto_rawDescData
}

var file_protos_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_orchestrator_proto_goTypes = []any{
	(Status)(0),              // 0: orchestrator.status
	(*Empty)(nil),            // 1: orchestrator.Empty
	(*Id)(nil),               // 2: orchestrator.Id
	(*StringExpression)(nil), // 3: orchestrator.StringExpression
	(*Expression)(nil),       // 4: orchestrator.Expression
	(*Task)(nil),             // 5: orchestrator.Task
	(*Answer)(nil),           // 6: orchestrator.Answer
}
var file_protos_orchestrator_proto_depIdxs = []int32{
	0, // 0: orchestrator.Expression.status:type_name -> orchestrator.status
	1, // 1: orchestrator.OrchestratorService.GetExpressions:input_type -> orchestrator.Empty
	2, // 2: orchestrator.OrchestratorService.GetExpressionById:input_type -> orchestrator.Id
	3, // 3: orchestrator.OrchestratorService.AddToQueue:input_type -> orchestrator.StringExpression
	1, // 4: orchestrator.OrchestratorService.GiveTask:input_type -> orchestrator.Empty
	6, // 5: orchestrator.OrchestratorService.AnswerTask:input_type -> orchestrator.Answer
	4, // 6: orchestrator.OrchestratorService.GetExpressions:output_type -> orchestrator.Expression
	4, // 7: orchestrator.OrchestratorService.GetExpressionById:output_type -> orchestrator.Expression
	4, // 8: orchestrator.OrchestratorService.AddToQueue:output_type -> orchestrator.Expression
	5, // 9: orchestrator.OrchestratorService.GiveTask:output_type -> orchestrator.Task
	1, // 10: orchestrator.OrchestratorService.AnswerTask:output_type -> orchestrator.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_orchestrator_proto_init() }
func file_protos_orchestrator_proto_init() {
	if File_protos_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_orchestrator_proto_rawDesc), len(file_protos_orchestrator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_orchestrator_proto_goTypes,
		DependencyIndexes: file_protos_orchestrator_proto_depIdxs,
		EnumInfos:         file_protos_orchestrator_proto_enumTypes,
		MessageInfos:      file_protos_orchestrator_proto_msgTypes,
	}.Build()
	File_protos_orchestrator_proto = out.File
	file_protos_orchestrator_proto_goTypes = nil
	file_protos_orchestrator_proto_depIdxs = nil
}
